* Transactional FS

TransactionalFS is a declarative and safe file system operations script designed to handle file and directory manipulations in a transactional manner. Users can define a series of operations, such as creating directories (~mkdir~), creating files with content (~spit~), setting executable permissions, and deleting files (~rm~) or directories (~rmdir~), including recursive deletions. These operations are validated and accumulated without side effects until the ~commit~ function is called, ensuring that all changes are applied atomically. This approach is particularly advantageous for testing environments, where operations can be verified in a mock directory before committing, allowing for controlled, repeatable, and safe tests without affecting the actual file system.

** TODO Instructions vs VFS
Instructions is what we produce currently.
VFS is the directory tree just like it'd be on the FS, but in memory. We can query it like (vfs/file-exists? vfs "path/test.txt").
(commit (mkvfs instructions))
  THIS MAY NOT BE NECESSARY NOW, but for testing it's definitely useful. And even just as a way of validating.

This instruction:
#+begin_src clojure
  {:path "a/b/c" :parents true :executable true :content "#!/usr/bin/env bb\n(println (+ 1 2))\n"}
#+end_src

Generates this VFS:
#+begin_src clojure
  [{:path "a" :type :directory}
   {:path "a/b" :type :directory}
   {:path "a/b/c" :type :file :executable true}]
#+end_src

Instructions can create and then delete, VFS is always the final state.

** Usage
*** In code
#+begin_src clojure
  (ns myapp.test
    (:require [clojure.test :refer :all]
              [jakub-stastny.transactional-fs.core :as tfs]))

  ;; Return a list of changes.
  (def black-box []
    [(tfs/mkdir "my/path" :parents true)
     (tfs/spit "my/path/test-file.txt" "Hello, World!")])

  (deftest file-creation-test
    (let [vfs (black-box)
          test-file (first (find #(= :path "my/path/test-file.txt")))]
      (is (= "Hello, World!") (:content test-file))))
#+end_src

*** In tests
#+begin_src clojure
  (let [changes [(mkdir "my/path" :parents true)
                 (spit "my/path/file.txt" "lorem ipsum")
                 (spit "my/path/executable.sh" "#!/bin/bash\necho Hello" :executable true)
                 (rm "my/path/file.txt")
                 (rmdir "my/path")
                 (rmdir "my/another/path" :recursive true)]]
    (commit "/tmp/transactional-root" changes))
#+end_src

** Implementation
#+begin_src clojure :tangle ../src/jakub_stastny/transactional_fs/core.clj :mkdirp yes :ns jakub-stastny.transactional-fs.core
  (ns jakub-stastny.transactional-fs.core
    (:require [babashka.fs :as fs]))

  (defn create-change [type path & {:keys [content parents executable recursive] :or {parents false executable false recursive false}}]
    (let [base-change {:type type :path path}
          base-change (if parents (assoc base-change :parents true) base-change)
          base-change (if executable (assoc base-change :executable true) base-change)
          base-change (if recursive (assoc base-change :recursive true) base-change)]
      (if (= type :create-file)
        (assoc base-change :content content)
        base-change)))

  (defn mkdir
    [path & {:keys [parents] :or {parents false}}]
    (create-change :create-directory path :parents parents))

  (defn spit
    [path content & {:keys [parents executable] :or {parents false executable false}}]
    (create-change :create-file path :content content :parents parents :executable executable))

  (defn rm [path]
    (create-change :delete-file path))

  ;; Note that to recursively delete a directory it's rmdir path :recursive true, not rm as it'd be on Unix.
  (defn rmdir
    [path & {:keys [recursive] :or {recursive false}}]
    (create-change :delete-directory path :recursive recursive))

  (defn validate-change [change]
    (let [{:keys [type path]} change]
      (cond
        (nil? type) (throw (ex-info "Change must have a type" {:change change}))
        (nil? path) (throw (ex-info "Change must have a path" {:change change}))
        (and (= type :create-file) (nil? (:content change))) (throw (ex-info "Create file change must have content" {:change change}))
        :else true)))

  (defn validate-changes [changes]
    (every? validate-change changes))

  (defn apply-change [change root]
    (let [{:keys [type path content parents executable recursive]} change
          full-path (fs/path root path)]
      (case type
        :create-file
        (do
          (when parents
            (fs/create-dirs (fs/parent full-path)))
          (fs/spit full-path content)
          (when executable
            (fs/set-posix-file-permissions full-path (fs/posix-file-permissions "rwxr-xr-x"))))

        :delete-file
        (fs/delete full-path)

        :create-directory
        (if parents
          (fs/create-dirs full-path)
          (fs/create-dir full-path))

        :delete-directory
        (if recursive
          (fs/delete full-path {:recursive true})
          (fs/delete full-path)))))

  (defn commit [root changes]
    (when (validate-changes changes)
      (doseq [change changes]
        (apply-change change root))))

  ;; TODO: Extract out as a standalone project or find if there's one already,
  ;; it's pretty useful.
  (defn commit-fs-change [output-dir {:keys [path code]}]
    (let [full-path (str output-dir "/" path)]
      (println (str "~ " path))
      ;; FIXME: No append, fail if file is to be overriden.
      (spit full-path code :append true)))

  ;; {path: string :content string :permissions 755}
  (defn commit-fs-changes [output-dir blocks]
    ;;(ensure-dir-exists (dirname path))
    (doseq [block blocks]
      (commit-fs-change output-dir block)))
#+end_src
