* Transactional FS

TransactionalFS is a declarative and safe file system operations script designed to handle file and directory manipulations in a transactional manner. Users can define a series of operations, such as creating directories (~mkdir~), creating files with content (~spit~), setting executable permissions, and deleting files (~rm~) or directories (~rmdir~), including recursive deletions. These operations are validated and accumulated without side effects until the ~commit~ function is called, ensuring that all changes are applied atomically. This approach is particularly advantageous for testing environments, where operations can be verified in a mock directory before committing, allowing for controlled, repeatable, and safe tests without affecting the actual file system.

** TODO Instructions vs VFS
Instructions is what we produce currently.
VFS is the directory tree just like it'd be on the FS, but in memory. We can query it like (vfs/file-exists? vfs "path/test.txt").
(commit (mkvfs instructions))
  THIS MAY NOT BE NECESSARY NOW, but for testing it's definitely useful. And even just as a way of validating.

This instruction:
#+begin_src clojure
  {:path "a/b/c" :parents true :executable true :content "#!/usr/bin/env bb\n(println (+ 1 2))\n"}
#+end_src

Generates this VFS:
#+begin_src clojure
  [{:path "a" :type :directory}
   {:path "a/b" :type :directory}
   {:path "a/b/c" :type :file :executable true}]
#+end_src

Instructions can create and then delete, VFS is always the final state.

** Usage
*** In code
#+begin_src clojure
  (ns myapp.test
    (:require [clojure.test :refer :all]
              [jakub-stastny.transactional-fs.core :as tfs]))

  ;; Return a list of changes.
  (def black-box []
    [(tfs/mkdir "my/path" :parents true)
     (tfs/spit "my/path/test-file.txt" "Hello, World!")])

  (deftest file-creation-test
    (let [vfs (black-box)
          test-file (first (find #(= :path "my/path/test-file.txt")))]
      (is (= "Hello, World!") (:content test-file))))
#+end_src

*** In tests
#+begin_src clojure
  (let [changes [(mkdir "my/path" :parents true)
                 (spit "my/path/file.txt" "lorem ipsum")
                 (spit "my/path/executable.sh" "#!/bin/bash\necho Hello" :executable true)
                 (rm "my/path/file.txt")
                 (rmdir "my/path")
                 (rmdir "my/another/path" :recursive true)]]
    (commit "/tmp/transactional-root" changes))
#+end_src

** Tests
#+begin_src clojure :tangle ../test/jakub_stastny/transactional_fs/core_test.clj :mkdirp yes :ns jakub-stastny.transactional-fs.core-test
  (ns jakub-stastny.transactional-fs.core-test
    (:require [clojure.test :refer :all]
              [jakub-stastny.transactional-fs.core :refer :all]))

  (deftest mkdir-test
    (testing "mkdir without parents"
      (let [change (mkdir "mydir")]
        (is (= {:type :create-directory :path "mydir"} change))))

    (testing "mkdir with parents"
      (let [change (mkdir "a/b/c" :parents true)]
        (is (= {:type :create-directory :path "a/b/c" :parents true} change)))))

  (deftest write-test
    (testing "write without parents and executable"
      (let [change (write "myfile.txt" "Hello, World!")]
        (is (= {:type :write-file :path "myfile.txt" :content "Hello, World!"}
               change))))

    (testing "write with parents"
      (let [change (write "a/b/c.txt" "Hello, World!" :parents true)]
        (is (= {:type :write-file :path "a/b/c.txt" :content "Hello, World!" :parents true}
               change))))

    (testing "write with executable"
      (let [change (write "myfile.sh" "#!/bin/bash\necho Hello" :executable true)]
        (is (= {:type :write-file :path "myfile.sh" :content "#!/bin/bash\necho Hello" :executable true}
               change))))

    (testing "write with parents and executable"
      (let [change (write "a/b/c.sh" "#!/bin/bash\necho Hello" :parents true :executable true)]
        (is (= {:type :write-file :path "a/b/c.sh" :content "#!/bin/bash\necho Hello" :parents true :executable true}
               change)))))

  (deftest rm-test
    (testing "rm file"
      (let [change (rm "myfile.txt")]
        (is (= {:type :delete-file :path "myfile.txt"} change)))))

  (deftest rmdir-test
    (testing "rmdir without recursive"
      (let [change (rmdir "mydir")]
        (is (= {:type :delete-directory :path "mydir"} change))))

    (testing "rmdir with recursive"
      (let [change (rmdir "mydir" :recursive true)]
        (is (= {:type :delete-directory :path "mydir" :recursive true} change)))))

  (deftest validate-change-instruction-test
    (testing "validate-change-instruction with valid create-directory"
      (let [change (mkdir "mydir")]
        (is (true? (validate-change-instruction change)))))

    (testing "validate-change-instruction with valid write-file"
      (let [change (write "myfile.txt" "Hello, World!")]
        (is (true? (validate-change-instruction change)))))

    (testing "validate-change-instruction with valid delete-file"
      (let [change (rm "myfile.txt")]
        (is (true? (validate-change-instruction change)))))

    (testing "validate-change-instruction with valid delete-directory"
      (let [change (rmdir "mydir")]
        (is (true? (validate-change-instruction change)))))

    (testing "validate-change-instruction without type"
      (let [change {:path "mydir"}]
        (is (thrown-with-msg? clojure.lang.ExceptionInfo #"Change instruction must have a type"
                              (validate-change-instruction change)))))

    (testing "validate-change-instruction without path"
      (let [change {:type :create-directory}]
        (is (thrown-with-msg? clojure.lang.ExceptionInfo #"Change instruction must have a path"
                              (validate-change-instruction change)))))

    (testing "validate-change-instruction write-file without content"
      (let [change {:type :write-file :path "myfile.txt"}]
        (is (thrown-with-msg? clojure.lang.ExceptionInfo #"Create file change instruction must have content"
                              (validate-change-instruction change))))))
#+end_src

** Implementation
#+begin_src clojure :tangle ../src/jakub_stastny/transactional_fs/core.clj :mkdirp yes :ns jakub-stastny.transactional-fs.core
  (ns jakub-stastny.transactional-fs.core
    (:require [babashka.fs :as fs]))

  (defn- create-change-instruction [type path & {:keys [content parents executable recursive] :or {parents false executable false recursive false}}]
    (let [base-change-instruction {:type type :path path}
          base-change-instruction (if parents (assoc base-change-instruction :parents true) base-change-instruction)
          base-change-instruction (if executable (assoc base-change-instruction :executable true) base-change-instruction)
          base-change-instruction (if recursive (assoc base-change-instruction :recursive true) base-change-instruction)]
      (if (= type :write-file)
        (assoc base-change-instruction :content content)
        base-change-instruction)))

  (defn mkdir [path & {:keys [parents] :or {parents false}}]
    (create-change-instruction :create-directory path :parents parents))

  (defn write
    [path content & {:keys [parents executable] :or {parents false executable false}}]
    (create-change-instruction :write-file path :content content :parents parents :executable executable))

  (defn rm [path]
    (create-change-instruction :delete-file path))

  ;; Note that to recursively delete a directory it's rmdir path :recursive true, not rm as it'd be on Unix.
  (defn rmdir [path & {:keys [recursive] :or {recursive false}}]
    (create-change-instruction :delete-directory path :recursive recursive))

  (defn validate-change-instruction [change-instruction]
    (let [{:keys [type path]} change-instruction]
      (when-not type
        (throw (ex-info "Change instruction must have a type" {:change-instruction change-instruction})))
      (when-not path
        (throw (ex-info "Change instruction must have a path" {:change-instruction change-instruction})))
      (when (and (= type :write-file) (not (:content change-instruction)))
        (throw (ex-info "Create file change instruction must have content" {:change-instruction change-instruction})))
      true))

  (defn validate-change-instructions [change-instructions]
    (every? validate-change-instruction change-instructions))

  (defn apply-change-instruction [change-instruction root]
    (let [{:keys [type path content parents executable recursive]} change-instruction
          full-path (fs/path root path)]
      (case type
        :write-file
        (do
          (when parents
            (fs/create-dirs (fs/parent full-path)))
          (spit full-path content)
          (when executable
            (fs/set-posix-file-permissions full-path (fs/posix-file-permissions "rwxr-xr-x"))))

        :delete-file
        (fs/delete full-path)

        :create-directory
        (if parents
          (fs/create-dirs full-path)
          (fs/create-dir full-path))

        :delete-directory
        (if recursive
          (fs/delete full-path {:recursive true})
          (fs/delete full-path)))))

  (defn commit [root change-instructions]
    (when (validate-change-instructions change-instructions)
      (doseq [change-instruction change-instructions]
        (apply-change-instruction change-instruction root))))
#+end_src

#+begin_src clojure
  ;; TODO: Extract out as a standalone project or find if there's one already,
  ;; it's pretty useful.
  (defn commit-fs-change-instruction [output-dir {:keys [path code]}]
    (let [full-path (str output-dir "/" path)]
      (println (str "~ " path))
      ;; FIXME: No append, fail if file is to be overriden.
      (spit full-path code :append true)))

  ;; {path: string :content string :permissions 755}
  (defn commit-fs-change-instructions [output-dir blocks]
    ;;(ensure-dir-exists (dirname path))
    (doseq [block blocks]
      (commit-fs-change-instruction output-dir block)))
#+end_src
